name: Docker Build Rdev

on:
  pull_request:
    types: [ labeled, synchronize ]
    paths:
      - 'apiv2/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.sender) }}
      run: |
        echo "$GITHUB_CONTEXT"
  rdev_argus_builder:
    uses: ./.github/workflows/workflow-argus-docker-build.yaml
    secrets: inherit
    if: contains(github.event.pull_request.labels.*.name, 'stack') && github.event.pull_request.head.user.type != 'Bot'
    with:
      envs: rdev
      path_filters: 'apiv2/**'
