name: Docker Build Staging/Prod

on:
  push:
    branches:
      - main

jobs:
  argus_builder:
    runs-on: [ARM64, self-hosted, Linux]
    uses: ./.github/workflows/workflow-argus-docker-build.yaml
    secrets: inherit
    with:
      envs: staging,prod
      path_filters: '!.infra/**'
      branches: release-please--branches--main
