name: Docker Image Build

on:
  - push

jobs:
  rdev_argus_builder:
    uses: ./.github/workflows/workflow-argus-docker-build.yaml
    secrets: inherit
    with:
      envs: rdev
      path_filters: src/**,.github/**
      branches_ignore: main,release-please--branches--main
